#!/bin/bash
echo "Enter Crunchyroll series or episode URL:"
read URL

echo "Enter name of the series:"
read FOLDER
mkdir "$FOLDER"

echo "Enter in the video Quality (360, 480, 720, 1080):"
read QUALITY

youtube-dl $URL --write-sub --sub-lang enUS -f 'bestvideo[height<='$QUALITY']+bestaudio/best[height<='$QUALITY']' --cookies cookies.txt

for MP4 in ./*.mp4
do
    NAME=$(basename "$MP4" .mp4)
    mkvmerge -o "$NAME.mkv" "$NAME.mp4" "$NAME.enUS.ass"
    rm "$NAME.mp4"
    rm "$NAME.enUS.ass"
    mv "$NAME.mkv" "$FOLDER"
done
