#!/bin/bash
CONNECTED_DISPLAY=$(xrandr | grep " connected" | cut -d' ' -f1 | tail -1)
if [ $CONNECTED_DISPLAY ]; then
	xrandr --output $CONNECTED_DISPLAY --auto --above LVDS1
	xrandr --output LVDS1 --off
fi
