#!/bin/bash

LOCKIMAGE=$1

scrot /tmp/temp_lockscreen.png && convert /tmp/temp_lockscreen.png -blur 0x4 /tmp/temp_lockscreen.png

if [[ -f $LOCKIMAGE ]]; then
   convert /tmp/temp_lockscreen.png $LOCKIMAGE -gravity center -composite /tmp/temp_lockscreen.png
fi

i3lock -e -f -c 000000 -i /tmp/temp_lockscreen.png
