#!/bin/bash
if [ $1 ];then
	PAPE="$PWD/$1"
else
	IMG_DIR="/home/haru/pictures/papes/abstract-paintings"
	RAND_BG=$(ls "$IMG_DIR/" |sort -R |tail -1)
	PAPE="$IMG_DIR/$RAND_BG"
fi

nitrogen $PAPE --set-zoom-fill

cat << EOF > /home/haru/.config/nitrogen/bg-saved.cfg
[xin_-1]
file=$PAPE
mode=5
bgcolor=#000000
EOF

sudo cp "$PAPE" /usr/share/lightdm-webkit/themes/litarvan/img/background.b9890328.png
wait
